repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [ "--filter-files" ]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-typing-imports==1.10.0 ]

  - repo: https://github.com/python-poetry/poetry.git
    rev: 1.2.0
    hooks:
      - id: poetry-export
  - repo: https://github.com/bruno-fs/cachito.git
    rev: 736d7c5
    hooks:
      - id: update-build-requirements
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.8.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements-build.in
        args: [requirements-build.in, -o, requirements-build.txt, --allow-unsafe]
